# Generated by Django 3.2.9 on 2021-11-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('music_genre', models.CharField(max_length=50)),
                ('daily_practice_time', models.TimeField()),
                ('days', models.IntegerField()),
                ('days_practiced', models.IntegerField()),
            ],
        ),
    ]
