# Generated by Django 3.2.9 on 2021-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='daily_practice_time',
            field=models.IntegerField(),
        ),
    ]
