# Generated by Django 3.2.9 on 2021-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_daily_practice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
