# Generated by Django 3.2.9 on 2021-11-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_assignment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='daily_practice_time',
            new_name='dailyPracticeTime',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='days_practiced',
            new_name='daysPracticed',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='music_genre',
            new_name='musicGenre',
        ),
    ]
