# Generated by Django 3.2.9 on 2021-11-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20211129_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='dailyPracticeTime',
            new_name='daily_practice_time',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='daysPracticed',
            new_name='days_practiced',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='musicGenre',
            new_name='music_genre',
        ),
    ]
